### PR TITLE
Remove vendoring & bump go version to 1.16

### PR DESCRIPTION
**Pull request by bill3tt**
This PR removes vendored dependencies from the repo and bumps Go to 1.16 to match the version defined in the docker file.

I've opted for `-mod mod` build args instead of `vendor` which seemed like the most sensible option, but happy to be told otherwise :)

Integration tests passed locally.

### CODE REVIEW

**Review by squat — DISMISSED** [review]

**Comment by squat** [comment]
> Integration tests passed locally.

Why isn't CI running here on GitHub? Let's hold off on merging until CI is running again

**Review by squat — APPROVED** [review]
CI is running now
LGTM

**Comment by bill3tt** [comment]
@squat your review velocity is something I truly admire! I don't have perms to merge - please can you do the honors?

**Review by squat — APPROVED** [review]

**Comment by squat** [comment]
💞

**Pull request merged**
